# Generated by Django 4.0.10 on 2023-07-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Notes',
        ),
    ]
